Derrickma/fix v3 brick
easyops-cn/next-bricks pull request #1125
Opened 2024-06-24 02:54 UTC by MJmajiong

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [ ] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [ ] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [ ] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2024-06-24 03:33 UTC, lijmyeah commented on bricks/basic/src/editors/eo-checkbox/eoCheckbox.schema.tsx
> +      type: "string",
这里简单的string恐怕不行吧？即使是固定值，也应该是数组

应该是 mode == tags 的多选下拉？

进一步做得更好，还应该和options有联动

2024-06-24 03:36 UTC, lijmyeah commented on bricks/basic/src/editors/eo-checkbox/eoCheckbox.schema.tsx
> +      title: "多选框选项",
简化文案， 多选框选项 => 选项

2024-06-24 03:37 UTC, lijmyeah commented on bricks/basic/src/editors/eo-checkbox/eoCheckbox.schema.tsx
> +      decorator: "FormItemWithoutAdvanced",
这个直接做一个 选项 构件来承载？其它构件也能复用，比如 select

2024-06-24 03:41 UTC, lijmyeah submitted a review, later dismissed

2024-06-24 03:41 UTC, lijmyeah commented on bricks/basic/src/editors/eo-checkbox/eoCheckbox.schema.tsx
> +      name: "options",
这个 options 和上面是不是有重复？

2024-06-24 03:41 UTC, lijmyeah commented on bricks/basic/src/editors/eo-checkbox/eoCheckbox.schema.tsx
> +      name: "options",
另外这些复杂类型，即使直接用 editor，也可以通过 placeholder 给出示例的

2024-06-24 03:42 UTC, lijmyeah commented on bricks/basic/src/editors/eo-checkbox/eoCheckbox.schema.tsx
> +      name: "message",
同上，placeholder

2024-06-24 03:45 UTC, lijmyeah commented on bricks/basic/src/editors/eo-form/eoForm.schema.tsx
> +        name: "Select",
要加中文，水平、垂直、行内

2024-06-24 03:59 UTC, lijmyeah commented on bricks/basic/src/editors/eo-input/eoInput.schema.tsx
> +          options: [
这个 type，看起来很多，能力很强，但实际上应该用不上这么多？

1. 功能欠缺的，比如 type == range，不知道该怎么设置值范围，只能按默认的值范围 0 - 100
2. 看起来无效的，比如 type == tel，没看出来和普通input的区别在哪
3. 功能重复，比如 type == date，我们有 日期构件，而且样式也难看

精简一下，甚至考虑不在可视化编辑里体现

2024-06-24 04:03 UTC, lijmyeah commented on bricks/basic/src/editors/eo-input/eoInput.schema.tsx
> +          options: [
还有一些意义不明的，比如 checkbox 就只有一个勾选框、button，我估计不会用人这么用

2024-06-24 04:04 UTC, lijmyeah commented on bricks/basic/src/editors/eo-radio/eoRadio.schema.tsx
> +            "button",
中文

2024-06-24 04:06 UTC, lijmyeah commented on bricks/basic/src/editors/eo-switch/eoSwitch.schema.tsx
> +      name: "checkedIcon",
这里顺序要注意，相近的属性放一起。

选中文本
非选中文本
大小
选中图标
非选中图标

中间咋隔了个大小？

改成：

选中文本
选中图标
非选中文本
非选中图标
大小

2024-06-24 04:08 UTC, lijmyeah commented on bricks/basic/src/editors/eo-textarea/eoInput.schema.tsx
> +      title: "大小设置",
自适应大小设置

2024-06-24 04:09 UTC, lijmyeah commented on bricks/basic/src/editors/eo-textarea/eoInput.schema.tsx
> +export const eoTextareaSchema = {
这个文件名怎么是 eoInput.schema.tsx

2024-06-24 10:31 UTC, MJmajiong commented on bricks/basic/src/editors/eo-input/eoInput.schema.tsx
> +          options: [
噢 这个我去网易数帆看过了 他们只保留了text和password 这些属性其实本质是html的input标签的, 往里面透传, 可以仿照他的

2024-06-25 06:54 UTC, weareoutman requested changes

2024-06-25 06:54 UTC, weareoutman commented on bricks/basic/src/editors/eo-form/index.tsx
> +customEditors.define("eo-form-editor", EoFormComponent);
```suggestion
customEditors.define("eo-form", EoFormComponent);
```

2024-06-25 06:54 UTC, weareoutman commented on bricks/basic/src/editors/eo-checkbox/eoCheckbox.schema.tsx
> +      type: "string",
https://docs-preview-1125--next-bricks.netlify.app/playground/?mode=yaml&example=visual-builder%2Fproperty-editor%2Fbasic

切换到高级模式，options 为啥变成了字符串？

<img width="261" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/d9a4cb09-40c2-465d-a061-22229244dd4a">

2024-06-25 06:54 UTC, weareoutman commented on bricks/basic/src/editors/eo-checkbox/eoCheckbox.schema.tsx
> +      type: "string",
https://docs-preview-1125--next-bricks.netlify.app/playground/?mode=yaml&example=visual-builder%2Fproperty-editor%2Fbasic

@SailorF  看看：

1. 选 eo-checkbox，看不到“类型”这个表单项。
2. 再选下 eo-input-editor，页面会报错，表单空了；
3. 此时再选 eo-checkbox，重新看到了"类型“选项；
4. 然后“类型”选“default”，然后再点x清空选项，点切换到高级模式，会报错，表单空了

2024-06-25 09:51 UTC, merged