feat(): show-dialog 支持 delete 类型
easyops-cn/next-bricks pull request #228
Opened 2023-06-19 04:05 UTC by Nlicroshan

Closes NEXT_BUILDER-3248

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [ ] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [x] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [x] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [x] 给新特性添加了单元测试。
- [x] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2023-06-19 07:46 UTC, weareoutman requested changes

2023-06-19 07:46 UTC, weareoutman commented on bricks/basic/src/data-providers/show-dialog/show-dialog.tsx
> +  type?: "success" | "error" | "warn" | "info" | "confirm" | "delete";
在 example.yaml 里补下示例，后面 provider 也会有文档

2023-06-19 07:46 UTC, weareoutman commented on bricks/form/src/input/input.shadow.css
> +  display: inline-block;
@SailorF 后面看下其他表单构件是否也需要这个处理？理论上大部分构件都应该是 inline-block 的，除了部分明确的块级容器

2023-06-19 07:49 UTC, SailorF commented on bricks/form/src/input/input.shadow.css
> +  display: inline-block;
后续统一修改下

2023-06-19 08:01 UTC, Nlicroshan commented on bricks/basic/src/data-providers/show-dialog/show-dialog.tsx
> +  type?: "success" | "error" | "warn" | "info" | "confirm" | "delete";
done

2023-06-19 08:11 UTC, weareoutman commented on bricks/basic/src/data-providers/show-dialog/example.yaml
> +        content: Please enter cat.png to delete the file.
这里后面思考下如何对关键词进行高亮，在不引入 html 注入风险的前提下

2023-06-19 08:11 UTC, weareoutman approved these changes

2023-06-19 08:12 UTC, merged

2023-06-20 01:44 UTC, Nlicroshan commented on bricks/basic/src/data-providers/show-dialog/example.yaml
> +        content: Please enter cat.png to delete the file.
可以用模版这种方式？
useage:
```yaml
content: Please enter #{expect} to delete the file.
expect: cat.png
````
result:
```tsx
<div>Please enter <strong>cat.png</strong> to delete the file.</div>
```

2023-06-20 01:49 UTC, weareoutman commented on bricks/basic/src/data-providers/show-dialog/example.yaml
> +        content: Please enter cat.png to delete the file.
可以，但是建议换一种业界更常用的模板形式：

`Please enter {{expect}} to delete the file.`

2023-06-20 01:52 UTC, Nlicroshan commented on bricks/basic/src/data-providers/show-dialog/example.yaml
> +        content: Please enter cat.png to delete the file.
ok