feat(): monaco editor support parse yaml&highlight
easyops-cn/next-bricks pull request #289
Opened 2023-07-12 12:04 UTC by SailorF

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [x] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [x] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2023-07-13 01:13 UTC, weareoutman requested changes

2023-07-13 01:13 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
> +      yaml.load(value, {
后面把 lint 工具的计算逻辑都放到 web worker 里，避免 lint 计算影响主线程，参考[这里](https://git.easyops.local/anyclouds/next-basics/blob/master/bricks/code/src/shared/analysis.worker.ts)。

2023-07-13 01:13 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
> +  const map = new BrickNextYamlSourceMap();
不需要 memo 一下吗？每次都是新的 map？

2023-07-13 01:13 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
> +        const markters = tokens
```suggestion
        const markers = tokens
```

2023-07-13 01:13 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
> +  const map = new BrickNextYamlSourceMap();
我看可以放进 parseYaml 里面，外面没有用到它。

2023-07-13 01:13 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
> +            }),
为啥要做这个替换？

2023-07-13 01:39 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
>  }
把 `tokenConf` 换成两个独立的属性吧：`markers` 和 `links` 分别用于 lint marker 和 link。

另外把 `highlight.click` 事件换成 `token.click`，这个不算是 highlight，后面可能会有真正的 highlight：

<img width="282" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/ae2dbce4-4e15-4b44-a0d3-0a1b74ad6a49">

2023-07-13 01:42 UTC, SailorF commented on bricks/vs/src/code-editor/index.tsx
> +            }),
有这种场景： <% 后面带空格
```
- a: |
    <% 
         CTX.a
    %>
```
parse的时候会 CTX 的 line 会变成2，导致行数识别错误，所以要清除 <% 后的空格

2023-07-13 01:47 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
> +            }),
那也最好不要在这里做替换，而是改为计算 `result.prefix` 占用的行数就好了

2023-07-13 02:01 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
> +          monaco.editor.setModelMarkers(
markers 没有进行清理：（删除 `<% %>` 使他变成普通字符串）

<img width="156" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/6e663e0b-9627-4148-bd8c-b317c7ec39ce">

2023-07-13 02:02 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
> +          monaco.editor.setModelMarkers(
decorations 也一样：

<img width="166" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/328b84cb-c160-4844-a6a0-19c4c96bf59a">

2023-07-13 03:17 UTC, weareoutman requested changes

2023-07-13 03:17 UTC, weareoutman commented on bricks/vs/docs/code-editor.md
> +    tokenConf:
示例没更新

2023-07-13 03:17 UTC, weareoutman commented on bricks/vs/docs/code-editor.md
> +    advancdCompleters:
同

2023-07-13 03:19 UTC, weareoutman commented
识别有误：

<img width="142" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/675c067b-efd6-4f80-9501-0d083c7303b9">

见 [Playgound](https://docs-preview-289--next-bricks.netlify.app/playground/#eyJ5YW1sIjoiLSBicmljazogdnMuY29kZS1lZGl0b3JcbiAgZXZlbnRzOlxuICAgIGhpZ2hsaWdodC5jbGljazpcbiAgICAgIC0gYWN0aW9uOiBjb25zb2xlLmxvZ1xuICBwcm9wZXJ0aWVzOlxuICAgIGxhbmd1YWdlOiBicmlja19uZXh0X3lhbWxcbiAgICB2YWx1ZTogfFxuICAgICAgYmFzaWNVc2lnZTpcbiAgICAgICAga2V5d29yZDpcbiAgICAgICAgIEV4cHJlc3Npb246XG4gICAgICAgICAgZXhwcmVzc2lvbjE6IDwlIENUWC53b3JrICU+XG4gICAgICAgICAgZXhwcmVzc2lvbjI6IDwlIGAke0NUWC53b3JrfWAgJT5cbiAgICAgICAgICBleHByZXNzaW9uMzogfFxuICAgICAgICAgICAgPCUgXG4gICAgICAgICAgICAgIENUWC5hID8gQ1RYLmIgOiBDVFguYyBcbiAgICAgICAgICAgICU+XG4gICAgICAgICAgZXhwcmVzc2lvbjQ6IFwiPCUgQ1RYLmEgPyBDVFguYiA6IENUWC5jICU+XCJcbiAgICAgICAgICBleHByZXNzaW9uNzogPCUgQ1RYLmxpc3QubWFwKGl0ZW0gPT4gRk4uZ2V0RGV0YWlsKGl0ZW0sIENUWC5uYW1lKSkgJT5cbiAgICAgICAgICBleHByZXNzaW9uODogPCUgQ1RYLmxpc3QubWFwKEZOLmdldERldGFpbCkgJT5cbiAgICAgICAgICBleHByZXNzaW9uOTogfFxuICAgICAgICAgICAgPCUgXG4gICAgICAgICAgICAgIFtcbiAgICAgICAgICAgICAgICBDVFgud29yayxcbiAgICAgICAgICAgICAgICBDVFgud29yay5hLFxuICAgICAgICAgICAgICAgIEFDVFgsXG4gICAgICAgICAgICAgICAgQ1RYQSxcbiAgICAgICAgICAgICAgICBBQ1RYLm5vV29yayxcbiAgICAgICAgICAgICAgICBDVFhBLm5vV29yayxcbiAgICAgICAgICAgICAgICBhLkNUWC5ub1dvcmssXG4gICAgICAgICAgICAgIF1cbiAgICAgICAgICAgICU+XG4gICAgICAgICAgZXhwcmVzc2lvbjEwOiB8XG4gICAgICAgICAgICA8JSBcbiAgICAgICAgICAgICAgXCJUUEwgaXMgd2FyblwiLCBcbiAgICAgICAgICAgICAgVFBMLmlkIFxuICAgICAgICAgICAgJT5cbiAgICAgICAgICBleHByZXNzaW9uMTE6IHxcbiAgICAgICAgICAgIDwlXG4gICAgICAgICAgICAgIEZOLmdldERldGFpbChDVFguYWJjLCBDVFguZWZnKSAlPlxuICAgICAgICAgIGV4cHJlc3Npb24xMjpcbiAgICAgICAgICAgIHRlc3QxOlxuICAgICAgICAgICAgICB0ZXN0MjogICAgICAgICAgPCUgIENUWC5uYW1lICU+XG4gICAgICAgICAgICAgIHRlc3QzOiB8XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8JSBcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgQ1RYLm5hbWVcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICU+XG4gICAgICAgICAgZXhwcmVzc2lvbjEzOiA8JT0gQ1RYLmIgKyBDVFguYyAlPlxuICAgICAgICAgIGV4cHJlc3Npb24xNDogfFxuICAgICAgICAgICAgPCU9XG4gICAgICAgICAgICAgIEFQUC5pZCArIENUWC5uYW1lXG4gICAgICAgICAgICAlPlxuICAgICAgICB0b2tlbkNvbmY6XG4gICAgICAgICAgaGl0OlxuICAgICAgICAgICAgUEFUSDogPCUgUEFUSC5pbnN0YW5jZUlkICU+XG4gICAgICAgICAgaW5mbzpcbiAgICAgICAgICAgIFFVRVJZOiA8JSBRVUVSWS5pbmZvICU+XG4gICAgICAgICAgd2FybjpcbiAgICAgICAgICAgIEFOQ0hPUjogPCUgQU5DSE9SLmlkICU+XG4gICAgICAgICAgZXJyb3I6XG4gICAgICAgICAgICBTVEFURTogfFxuICAgICAgICAgICAgICA8JVxuICAgICAgICAgICAgICAgIFNUQVRFLm5hbWVcbiAgICAgICAgICAgICAgJT5cbiAgICAgICAgc3RyaW5nQW5kTm9Xb3JrOlxuICAgICAgICAgIHN0cmluZzE6IENUWC5ub1dvcmtcbiAgICAgICAgICBzdHJpbmcyOiBGTi5nZXRUZXN0XG4gICAgICAgICAgc3RyaW5nMzogPCUgXCJGTi5nZXRUZXN0KENUWC50ZXN0KVwiICU+XG4gICAgYXV0b21hdGljTGF5b3V0OiBmaXQtY29udGVudFxuICAgIG1hcmtlcnM6XG4gICAgICAtIHRva2VuOiBQQVRIXG4gICAgICAgIG1lc3NhZ2U6IOKAnOi/meaYryBQQVRI4oCdXG4gICAgICAgIGxldmVsOiBoaXRcbiAgICAgIC0gdG9rZW46IFFVRVJZXG4gICAgICAgIG1lc3NhZ2U6IOKAnOi/meaYryBRVUVSWeKAnVxuICAgICAgICBsZXZlbDogaW5mb1xuICAgICAgLSB0b2tlbjogQU5DSE9SXG4gICAgICAgIG1lc3NhZ2U6IOKAnOi/meaYryBBTkNIT1LigJxcbiAgICAgICAgbGV2ZWw6IHdhcm5cbiAgICAgIC0gdG9rZW46IFNUQVRFXG4gICAgICAgIG1lc3NhZ2U6IFwi6L+Z6YeM5LiN6IO95YaZIFNUQVRFXCJcbiAgICAgICAgbGV2ZWw6IGVycm9yXG4gICAgICAgIGNvZGU6XG4gICAgICAgICAgdmFsdWU6IFwi6K+m5oOF5Zyw5Z2AXCJcbiAgICAgICAgICB0YXJnZXQ6IGh0dHBzOi8vYnJpY2stbmV4dC5qcy5vcmcvZG9jcy9jb25jZXB0cy9jb250ZXh0XG4gICAgICAtIHRva2VuOiBUUExcbiAgICAgICAgbGV2ZWw6IHdhcm5cbiAgICAgICAgbWVzc2FnZTog5LiN5YWB6K645YaZ5YWlVFBMXG4gICAgbGlua3M6XG4gICAgICAtIENUWFxuICAgICAgLSBGTlxuICAgIGNvbXBsZXRlcnM6XG4gICAgICAtIGxhYmVsOiBidXR0b25OYW1lXG4gICAgICAgIGRldGFpbDogc3RyaW5nXG4gICAgICAtIGxhYmVsOiBidXR0b25UeXBlXG4gICAgICAgIGRldGFpbDogXCJwcmltYXJ5fGRlZmF1bHR8bGlua3xkYW5nZXJcIlxuICAgICAgLSBsYWJlbDogYnV0dG9uU2l6ZVxuICAgICAgICBpbnNlcnRUZXh0OiBzaXplXG4gICAgYWR2YW5jZENvbXBsZXRlcnM6XG4gICAgICB0YXJnZXQ6XG4gICAgICAgIHRyaWdnZXJDaGFyYWN0ZXI6IFwiOlwiXG4gICAgICAgIGNvbXBsZXRlcnM6XG4gICAgICAgICAgLSBsYWJlbDogYVxuICAgICAgICAgIC0gbGFiZWw6IGJcbiAgICAgIENUWDpcbiAgICAgICAgdHJpZ2dlckNoYXJhY3RlcjogXCIuXCJcbiAgICAgICAgY29tcGxldGVyczpcbiAgICAgICAgICAtIGxhYmVsOiBwYWdlVGl0bGVcbiAgICAgICAgICAtIGxhYmVsOiBuYW1lXG4gICAgICBGTjpcbiAgICAgICAgdHJpZ2dlckNoYXJhY3RlcjogXCIuXCJcbiAgICAgICAgY29tcGxldGVyczpcbiAgICAgICAgICAtIGxhYmVsOiBnZXRQYWdlRGV0YWlsXG4gICAgICAgICAgLSBsYWJlbDogZ2V0SW5zdGFuY2VcbiAgICAgIFBBVEg6XG4gICAgICAgIHRyaWdnZXJDaGFyYWN0ZXI6IFwiLlwiXG4gICAgICAgIGNvbXBsZXRlcnM6XG4gICAgICAgICAgLSBsYWJlbDogaW5zdGFuY2VJZFxuICAgICAgICAgIC0gbGFiZWw6IG5hbWUiLCJnYXAiOmZhbHNlfQ==)

2023-07-13 03:22 UTC, weareoutman commented
[这个](https://docs-preview-289--next-bricks.netlify.app/playground/#eyJ5YW1sIjoiLSBicmljazogdnMuY29kZS1lZGl0b3JcbiAgZXZlbnRzOlxuICAgIGhpZ2hsaWdodC5jbGljazpcbiAgICAgIC0gYWN0aW9uOiBjb25zb2xlLmxvZ1xuICBwcm9wZXJ0aWVzOlxuICAgIGxhbmd1YWdlOiBicmlja19uZXh0X3lhbWxcbiAgICB2YWx1ZTogfFxuICAgICAgYmFzaWNVc2lnZTpcbiAgICAgICAga2V5d29yZDpcbiAgICAgICAgIEV4cHJlc3Npb246XG4gICAgICAgICAgZXhwcmVzc2lvbjE6IHxcbiAgICAgICAgICAgIDwlXG4gICAgICAgICAgICAgIENUWC53b3JrICU+XG4gICAgICAgICAgZXhwcmVzc2lvbjI6IDwlIGAke0NUWC53b3JrfWAgJT5cbiAgICAgICAgICBleHByZXNzaW9uMzogfFxuICAgICAgICAgICAgPCUgXG4gICAgICAgICAgICAgIENUWC5hID8gQ1RYLmIgOiBDVFguYyBcbiAgICAgICAgICAgICU+XG4gICAgICAgICAgZXhwcmVzc2lvbjQ6IFwiPCUgQ1RYLmEgPyBDVFguYiA6IENUWC5jICU+XCJcbiAgICAgICAgICBleHByZXNzaW9uNzogPCUgQ1RYLmxpc3QubWFwKGl0ZW0gPT4gRk4uZ2V0RGV0YWlsKGl0ZW0sIENUWC5uYW1lKSkgJT5cbiAgICAgICAgICBleHByZXNzaW9uODogPCUgQ1RYLmxpc3QubWFwKEZOLmdldERldGFpbCkgJT5cbiAgICAgICAgICBleHByZXNzaW9uOTogfFxuICAgICAgICAgICAgPCUgXG4gICAgICAgICAgICAgIFtcbiAgICAgICAgICAgICAgICBDVFgud29yayxcbiAgICAgICAgICAgICAgICBDVFgud29yay5hLFxuICAgICAgICAgICAgICAgIEFDVFgsXG4gICAgICAgICAgICAgICAgQ1RYQSxcbiAgICAgICAgICAgICAgICBBQ1RYLm5vV29yayxcbiAgICAgICAgICAgICAgICBDVFhBLm5vV29yayxcbiAgICAgICAgICAgICAgICBhLkNUWC5ub1dvcmssXG4gICAgICAgICAgICAgIF1cbiAgICAgICAgICAgICU+XG4gICAgICAgICAgZXhwcmVzc2lvbjEwOiB8XG4gICAgICAgICAgICA8JSBcbiAgICAgICAgICAgICAgXCJUUEwgaXMgd2FyblwiLCBcbiAgICAgICAgICAgICAgVFBMLmlkIFxuICAgICAgICAgICAgJT5cbiAgICAgICAgICBleHByZXNzaW9uMTE6IHxcbiAgICAgICAgICAgIDwlXG4gICAgICAgICAgICAgIEZOLmdldERldGFpbChDVFguYWJjLCBDVFguZWZnKSAlPlxuICAgICAgICAgIGV4cHJlc3Npb24xMjpcbiAgICAgICAgICAgIHRlc3QxOlxuICAgICAgICAgICAgICB0ZXN0MjogICAgICAgICAgPCUgIENUWC5uYW1lICU+XG4gICAgICAgICAgICAgIHRlc3QzOiB8XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8JSBcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgQ1RYLm5hbWVcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICU+XG4gICAgICAgICAgZXhwcmVzc2lvbjEzOiA8JT0gQ1RYLmIgKyBDVFguYyAlPlxuICAgICAgICAgIGV4cHJlc3Npb24xNDogfFxuICAgICAgICAgICAgPCU9XG4gICAgICAgICAgICAgIEFQUC5pZCArIENUWC5uYW1lXG4gICAgICAgICAgICAlPlxuICAgICAgICB0b2tlbkNvbmY6XG4gICAgICAgICAgaGl0OlxuICAgICAgICAgICAgUEFUSDogPCUgUEFUSC5pbnN0YW5jZUlkICU+XG4gICAgICAgICAgaW5mbzpcbiAgICAgICAgICAgIFFVRVJZOiA8JSBRVUVSWS5pbmZvICU+XG4gICAgICAgICAgd2FybjpcbiAgICAgICAgICAgIEFOQ0hPUjogPCUgQU5DSE9SLmlkICU+XG4gICAgICAgICAgZXJyb3I6XG4gICAgICAgICAgICBTVEFURTogfFxuICAgICAgICAgICAgICA8JVxuICAgICAgICAgICAgICAgIFNUQVRFLm5hbWVcbiAgICAgICAgICAgICAgJT5cbiAgICAgICAgc3RyaW5nQW5kTm9Xb3JrOlxuICAgICAgICAgIHN0cmluZzE6IENUWC5ub1dvcmtcbiAgICAgICAgICBzdHJpbmcyOiBGTi5nZXRUZXN0XG4gICAgICAgICAgc3RyaW5nMzogPCUgXCJGTi5nZXRUZXN0KENUWC50ZXN0KVwiICU+XG4gICAgYXV0b21hdGljTGF5b3V0OiBmaXQtY29udGVudFxuICAgIG1hcmtlcnM6XG4gICAgICAtIHRva2VuOiBQQVRIXG4gICAgICAgIG1lc3NhZ2U6IOKAnOi/meaYryBQQVRI4oCdXG4gICAgICAgIGxldmVsOiBoaXRcbiAgICAgIC0gdG9rZW46IFFVRVJZXG4gICAgICAgIG1lc3NhZ2U6IOKAnOi/meaYryBRVUVSWeKAnVxuICAgICAgICBsZXZlbDogaW5mb1xuICAgICAgLSB0b2tlbjogQU5DSE9SXG4gICAgICAgIG1lc3NhZ2U6IOKAnOi/meaYryBBTkNIT1LigJxcbiAgICAgICAgbGV2ZWw6IHdhcm5cbiAgICAgIC0gdG9rZW46IFNUQVRFXG4gICAgICAgIG1lc3NhZ2U6IFwi6L+Z6YeM5LiN6IO95YaZIFNUQVRFXCJcbiAgICAgICAgbGV2ZWw6IGVycm9yXG4gICAgICAgIGNvZGU6XG4gICAgICAgICAgdmFsdWU6IFwi6K+m5oOF5Zyw5Z2AXCJcbiAgICAgICAgICB0YXJnZXQ6IGh0dHBzOi8vYnJpY2stbmV4dC5qcy5vcmcvZG9jcy9jb25jZXB0cy9jb250ZXh0XG4gICAgICAtIHRva2VuOiBUUExcbiAgICAgICAgbGV2ZWw6IHdhcm5cbiAgICAgICAgbWVzc2FnZTog5LiN5YWB6K645YaZ5YWlVFBMXG4gICAgbGlua3M6XG4gICAgICAtIENUWFxuICAgICAgLSBGTlxuICAgIGNvbXBsZXRlcnM6XG4gICAgICAtIGxhYmVsOiBidXR0b25OYW1lXG4gICAgICAgIGRldGFpbDogc3RyaW5nXG4gICAgICAtIGxhYmVsOiBidXR0b25UeXBlXG4gICAgICAgIGRldGFpbDogXCJwcmltYXJ5fGRlZmF1bHR8bGlua3xkYW5nZXJcIlxuICAgICAgLSBsYWJlbDogYnV0dG9uU2l6ZVxuICAgICAgICBpbnNlcnRUZXh0OiBzaXplXG4gICAgYWR2YW5jZENvbXBsZXRlcnM6XG4gICAgICB0YXJnZXQ6XG4gICAgICAgIHRyaWdnZXJDaGFyYWN0ZXI6IFwiOlwiXG4gICAgICAgIGNvbXBsZXRlcnM6XG4gICAgICAgICAgLSBsYWJlbDogYVxuICAgICAgICAgIC0gbGFiZWw6IGJcbiAgICAgIENUWDpcbiAgICAgICAgdHJpZ2dlckNoYXJhY3RlcjogXCIuXCJcbiAgICAgICAgY29tcGxldGVyczpcbiAgICAgICAgICAtIGxhYmVsOiBwYWdlVGl0bGVcbiAgICAgICAgICAtIGxhYmVsOiBuYW1lXG4gICAgICBGTjpcbiAgICAgICAgdHJpZ2dlckNoYXJhY3RlcjogXCIuXCJcbiAgICAgICAgY29tcGxldGVyczpcbiAgICAgICAgICAtIGxhYmVsOiBnZXRQYWdlRGV0YWlsXG4gICAgICAgICAgLSBsYWJlbDogZ2V0SW5zdGFuY2VcbiAgICAgIFBBVEg6XG4gICAgICAgIHRyaWdnZXJDaGFyYWN0ZXI6IFwiLlwiXG4gICAgICAgIGNvbXBsZXRlcnM6XG4gICAgICAgICAgLSBsYWJlbDogaW5zdGFuY2VJZFxuICAgICAgICAgIC0gbGFiZWw6IG5hbWUiLCJnYXAiOmZhbHNlfQ==)也有问题：

<img width="318" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/f48d34ab-2894-49de-b101-30d5752de56c">

2023-07-13 03:43 UTC, SailorF commented on bricks/vs/src/code-editor/index.tsx
> +            }),
这段逻辑还是需要保留，因为 `<%` & `<%\n` 识别出的 CTX 的位置是 line: 1, 而 `<% ` & `<%  \n` 识别的 CTX line 是 2，直接在 souce 这里处理会比较好

2023-07-13 03:50 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
> +            }),
怎么会呢，可以根据 prefix 获得准确的相对位置吧？

2023-07-13 06:51 UTC, weareoutman requested changes

2023-07-13 06:51 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
> +                const hadWrap = /<%[ ]+/.test(result.prefix);
不清楚为啥要这么处理，目前还有问题，给多行的 `<%` 前面加个空格：

<img width="213" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/6f53b94e-b7ce-4381-b279-04d00080206e">

或者给多行的 `<%` 第一行不换行：

<img width="276" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/5002f7fd-c6ea-416d-bf99-05f43a2b96a5">


我理解这里只需要计算 `result.prefix` 偏移的行数和列数就好了

2023-07-13 06:55 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
> +                const hadWrap = /<%[ ]+/.test(result.prefix);
对于上面的第二个问题，应该是还要计算 yaml 里多行字符串造成的列偏移

2023-07-13 06:56 UTC, SailorF commented on bricks/vs/src/code-editor/index.tsx
> +                const hadWrap = /<%[ ]+/.test(result.prefix);
第一个给多行 `<%` 前加空格会导致 yaml 格式错误，格式错误是不做高亮等特殊处理；
下面那个我看下

2023-07-13 07:27 UTC, weareoutman commented on bricks/vs/src/code-editor/index.tsx
> +                const hadWrap = /<%[ ]+/.test(result.prefix);
另外，使用 `|-` 或 `>-` 也有问题

<img width="233" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/1da2d712-72ce-4af3-9974-0dbb9f0df41d">

2023-07-13 07:49 UTC, SailorF commented on bricks/vs/src/code-editor/index.tsx
> +                const hadWrap = /<%[ ]+/.test(result.prefix);
这里的计算其实很别扭，应该多行表达式在 yaml.safeload 解析后，它的 position 和 lineStart 是相等的，不同于单行表达式，他们之间的表现形式是有差异的；另外，`<%` & `<%\n` 的表现形式是相同的， `<% ` 和 `<% \n` 的表现形式也是相同的，所以要区分，以下是示例场景：
- `<%` 与 `<%\n` 不带空格
   ```
  a: | 
     <%
         CTX.a，
         CTX.b
     %>
  ```
  解析后此时的 startLine等于 2， endLine 等于 5
  此时 CTX.a 的 loc.start.line 为1, CTX.b 的 loc.start.line 为 2, 而 `result.prefix` 为 `  <%\n`, `result.souce`: "      CTX.a,\n      CTX.b \n";
  
  
-  `<%` 与 `<%\n` 带空格
   ```
  a: | 
     <% 
         CTX.c，
         CTX.d
     %>
  ```
  解析后此时的 startLine等于 2， endLine 等于 5
  此时 CTX.c 的 loc.start.line 为 2, CTX.d 的 loc.start.line 为 3, 而 `result.prefix` 为 `  <%  `, `result.souce`: "      
 \n      CTX.a,\n      CTX.b \n";
  

所以我这里就直接判断了 `<%` 是否带空格, 有的话则需要在计算的时候给每行都减去 1

2023-07-14 01:01 UTC, weareoutman approved these changes
先合了，后面拎出 worker，然后再补下单元测试

2023-07-14 01:01 UTC, merged