feat(nav-menu): add overflow style
easyops-cn/next-bricks pull request #563
Opened 2023-10-30 11:03 UTC by SailorF

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [x] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [x] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2023-10-30 11:47 UTC, weareoutman requested changes

2023-10-30 11:47 UTC, weareoutman commented on bricks/nav/src/nav-menu/index.tsx
> +  useEffect(() => {
这个 PR 是解决什么问题？能在文档里加个示例吗？

2023-10-31 02:18 UTC, SailorF commented on bricks/nav/src/nav-menu/index.tsx
> +  useEffect(() => {
新增导航省略能力，文档示例已经补充

2023-10-31 02:27 UTC, weareoutman commented on bricks/nav/src/nav-menu/index.tsx
> +  useEffect(() => {
在一定宽度下，省略号超出了容器：

<img width="354" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/15691909-1d2c-4a52-b430-7f28ecf99340">

https://docs-preview-563--next-bricks.netlify.app/playground/#gzip,H4sIAAAAAAAAE61UzW7TQBB+lZUlbrgJHPeGOCAOXDjnsvaO41XX3pU9jhshJASRQAIKCJULEgKhcuPnUoTSAy9Tu+UtWMuN2aZeByJyy8y33481M/e8OUukR70gE+EuJbn0cy0F+pqlICdpGAvJM0jpJCXEJ+coUH7KZn4CadHUiXmm0DxGlmFb0JnSkKGAnLYFg8G5hO4fIaXgGFNybTy+sio2hBYCBZoXJFHhLuEM2Z9OA7yNkOQWuvGHsGd8VE/e/nrw3u4YLkXJiK3V5trQc4hYIXGNqJU+O1rUy5fV8nXfw7wI7nRfYPUTl1zZzup3i5Pj75f4OoNBT91l8oLR6vDV6fLTyY/P1c9HDu7Qxd2bw53FzhMmPGil+1ArYQNytIeyXcjHYaZ0Pig1nGU4j50pkqp0Yc4TbYBsSmWroVJyg9oGyMAQtzP35nH94WPfaMQZRJRMvBhR09GoLMudgAle7IQqmXj/uiv1/mH1wujs1wff6udf/tPG3NCC3GIIJZs75ppvuzP10dOzrwenxwsXwTRThd5mLepnD82aD6wEbL8P1h0ZEIj+UqA76VzM7FMOKXce8sbCTZUipAZ4V0zjzur6iY+h6VJyfTzWe95Vb8q0RyMmc7j/G0Zrghp5BgAA

2023-10-31 02:29 UTC, weareoutman commented on bricks/nav/src/nav-menu/index.tsx
> +    <div ref={navMenuWrapperRef} key={menu?.title} className="nav-menu-wrapper">
这里加个 key 的原因是？

2023-10-31 02:32 UTC, SailorF commented on bricks/nav/src/nav-menu/index.tsx
> +    <div ref={navMenuWrapperRef} key={menu?.title} className="nav-menu-wrapper">
误传的代码，我干掉

2023-10-31 03:54 UTC, weareoutman commented on bricks/nav/docs/eo-nav-menu.md
>  ### 带网站地图的菜单
这个导航有点奇怪：

<img width="355" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/a66ebb72-034f-4d0e-ab13-02a1cc99f42c">

https://docs-preview-563--next-bricks.netlify.app/playground/?mode=yaml&example=nav%2Feo-nav-menu%2F%E5%B8%A6%E7%BD%91%E7%AB%99%E5%9C%B0%E5%9B%BE%E7%9A%84%E8%8F%9C%E5%8D%95

2023-10-31 03:55 UTC, weareoutman commented on bricks/nav/docs/eo-nav-menu.md
>  ### 带网站地图的菜单
对比之前的：

<img width="537" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/fafac9a3-ec7f-4063-84d3-1b8ead578da1">

https://bricks.js.org/playground/?mode=yaml&example=nav%2Feo-nav-menu%2F%E5%B8%A6%E7%BD%91%E7%AB%99%E5%9C%B0%E5%9B%BE%E7%9A%84%E8%8F%9C%E5%8D%95

2023-10-31 03:55 UTC, weareoutman commented on bricks/nav/docs/eo-nav-menu.md
>  ### 带网站地图的菜单
样式上有问题，另外并没有超出宽度，也被省略了

2023-10-31 03:56 UTC, weareoutman commented on bricks/nav/docs/eo-nav-menu.md
>  ### 带网站地图的菜单
所有示例似乎都被折叠了，即使去掉限宽 100px

2023-10-31 15:40 UTC, weareoutman commented
把网站地图的菜单项拷到 overflow 的例子了，往下滚动，搜索框会看起来在中间（上方漏出了部分文字），而不是顶部：

<img width="534" alt="image" src="https://github.com/easyops-cn/next-bricks/assets/2338946/15e6d4bc-015b-4d95-b4e6-240baab4d074">

https://docs-preview-563--next-bricks.netlify.app/playground/?mode=yaml&example=nav%2Feo-nav-menu%2Foverflow#gzip,H4sIAAAAAAAAE+1bW2/bNhT+K4KfNmyOHefSxm9d0Q0B1qFA97bsgaJom7AsChIVxxgGtLk0W9d2C7Z26ZJd0jZLsTVO261r4ywpsL+ySHL+RSn5MhsWRdeWPRQxHxLHOjzkOef7eA5J5bNYCRTUWDoWl2QDw3xaUvD8nCZJukF0ZFCMzLT3pySZtKSi+mdJyiGczdG0lEom9QXvS5jDqmIgrS7RVIdIXAPz8QLSrEbfDtWd6r1WxArNpaXxxgi15ilqE6OYso5SgcC8pAAKWp95wrMUFcy2Ht7sKFpgs7e/2Di58kv7M6aRpKUE6Pi2pLNhFJQBlko71NUmUX227FS+sSvfBnc2Lfliix8aDQfMsHWWzk/Lxwd/BWhtTlYOfMKfcNuk7e01t/Lr8Ytd++USdwTIH4FjVZhlrdbBgiLXphAs15gAE+MKhFvaZq2C5oluCgYU2SWyrdW+jEqKfKm6dUIhsYWtY1JCVOGYQqFQwNeQeWfV2bofDJ2cgTJpaS6Wo1RPJxLFYnFMBlixxiApzMV6YZdza9v+mo12y7n92LlZjpRj53QsfQAoKoISlwNKPyxznn1V3bvtHizzlWQNYum90si5scgWiVAKof7407IWhQ6T6WGY/9y0edO+vhUc2kD/+F/OKmnJQCaxDNhhpJ+YPgQlYrHpm8yVF0GHkhB0hEemTXmIAxv5obzllr9//RADSPE8urAAVUthWVP65FOej2uSs1pdMmypmIslGBV1i2ItG294L14gGqbESKgEAjWRIyZNpHVAc+90crZ9zIuAwtxlBAzIknYGqCYXbt06zWv1xxcWdKApSBFoRgtsLgIZDIkW4hfIFoEsMUoMK4hJKm2VC0eb5Lkp3pW8imVWEwGzxJIQd4aaSYEGkYfq6WRqWj6bnITjYHqa18EkBvUKJS7xfOoevzhwNitvOZuP7M3HJ0sP3cOnb4en3G7Q0cea0lI0hiA6j1gsxseSYxzzBsSOMOvzlowMDVFkJrIWVrhQew09/swAxUTrnbKB6kbsFbKXocGkyBg4gWHHnqLRagROCQh8snHNPXrQK2Vb0FE3eHjUHY+cukLJ7gH9ZoBUJ8qgASqnuBbVADohAOglElgi+wLdo1MP0RI5MlMjZLa0npCpEQUNHJoznEA1oDkpgGb1+qK7uB8BOj1rhwfPiRE8W1pv2Z1oFGBt8PldzggK9CkBRu3yvn33Ya8YVQjMIyPRNHd4IJ0MkvCfzsXY86DSU7ixbpxN7q7bi4Eu+X82zCbzNMiiTu9D2Yy80n4z+EURY4JG41AllhLPAUOJK9jMD5Bt0zAzLctTAraJEsLKUbW8d1xZ+3fpgP107191N9bPv3c5lH5h4R8W38YHsBEeJYWBwVQWbPq6ham9t199ssVfD/0u4RglQ8Ro4I6vmRPG+8kJ7uGae7A5xJxw6tihEqDIQPXQPEB+nIGpJDwLudcF3fHjz5+rh4f2j6vVrS139457ezuUHKyGLxIjH3Sg2TR5WCRJjRbyttYTVAGDHpBBvfpAKjAphnHdklX2C+uDhu/MBGeH1iV8T9ZfnqzeqFUh9t/7zpUde+URW+BmL/UGY+aOOMKBq6ffOXIIj072WlsEBbQGaDxbu4geOHhnzkRTm0j/PJc+Ovcxw6298kdvwM3y7979zpEDN/A8qVmgpPovUKrlI/vB6qhMqdvccWQiJ6fQWdGxnvBOs/LAuXnP2ax0hToFzWMYUBmbRcw8MyzsTZy6vB8ce9Fxmeg6rPp8z/3uiejETBR7xuUhXoVNnLqEGRj7mSnBrlh003Sy/tS9+rt9725fsc9ggyUdlfsWXPTRD886E/1knerqb3b5h+P9L92NNefWTpCkr+J9gxS812V9F4zSU93mAaUn/5WbvjA6zHdsJkeZKZLM5Fzfdu4Eln6+TDdhLyDTBNmhnUVMjvJSjfAcN3Sbly6wfdh5YvDj1k3shUoiD/5pewuCQ3vBdlj4jsHONXvjqK/Qz2PE/T+A6MMeeHbVrEYmvWok9m4sC/RY2vfn568AG/X8gC40AAA=

2023-11-01 03:49 UTC, weareoutman approved these changes

2023-11-01 03:49 UTC, merged